export const statesOfVenezuela = [
  "Amazonas", 
  "Anzoátegui", 
  "Apure", 
  "Aragua", 
  "Barinas", 
  "Bolívar", 
  "Carabobo", 
  "Cojedes", 
  "Delta Amacuro", 
  "Distrito Capital (Caracas)", 
  "Falcón", 
  "Guárico", 
  "Lara", 
  "Mérida", 
  "Miranda", 
  "Monagas", 
  "Nueva Esparta", 
  "Portuguesa", 
  "Sucre", 
  "Táchira", 
  "Trujillo", 
  "Vargas", 
  "Yaracuy",
  "Zulia"
]